# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='Billy', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
